"""remove unique constraint user id in pomodoroCycle

Revision ID: b5e7a62b5ca4
Revises: 07fda1024bd1
Create Date: 2025-11-29 18:56:19.858892

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b5e7a62b5ca4'
down_revision: Union[str, Sequence[str], None] = '07fda1024bd1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('pomodoro_cycle_user_id_key'), 'pomodoro_cycle', type_='unique')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(op.f('pomodoro_cycle_user_id_key'), 'pomodoro_cycle', ['user_id'], postgresql_nulls_not_distinct=False)
    # ### end Alembic commands ###
